### ISSUE TITLE
Only Seed Node is set to 127.0.0.1:19999, connection error when not passing option

### ISSUE THREAD

**Issue by cloudwheels** [dashevo/dapi-client#125]
### Expected Behavior

connect to evonet with dapi client without specifying seed node, i.e.
```
var client = new DAPIClient();
```
### Current Behavior
connection error `Error: connect ECONNREFUSED 127.0.0.1:3000`

### Context
Currently only seed node is set as `service: '127.0.0.1:19999',`
(v11 branch)
https://github.com/dashevo/dapi-client/blob/646009998ff61d1834a4c30de789649767172b5e/src/config.js#L15

Needs updating to an known IP or DNS name.

Also, currently only a single MN, should be an array to prevent single point of failure.

**Comment by antouhou** [comment]
Hi @cloudwheels ! Currently you need to specify the seed node directly, there's no DNS seeder for the EvoNet. IPs are dynamic and are changing from time to time until we've created a DNS seed. You can use any of the MNs on the EvoNet as a seed, for example `52.24.198.145` or `54.149.72.137`, i.e. `new DAPIClient({ seeds: [{service: '52.24.198.145'}, {service: '54.149.72.137'}] })`

**Comment by shumkov** [comment]
We are working on DNS seeds for evonet so will put it there when it ready.

**Comment by antouhou** [comment]
BTW evonet seed is working for a while. @cloudwheels can we close the issue?

**Comment by cloudwheels** [comment]
Thanks, yes, please close it!

**Comment by antouhou** [comment]
@cloudwheels Great, closing it!
